### ISSUE TITLE
SBTI pydantic error

### ISSUE THREAD

**Issue by VerdureClimateLtd** [ScienceBasedTargets/SBTi-finance-tool#330]
hi, i developed an app around SBTi temperature score logic, using WATS.
it works perfectly when i run locally, but after deploying the app, it gives the following error:

An error occurred: 2 validation errors for PortfolioCompany company_id Input should be a valid string [type=string_type, input_value=1, input_type=int] For further information visit https://errors.pydantic.dev/2.10/v/string_type user_fields Field required [type=missing, input_value={'company_name': 'Sterlin...y_isin': 'NGSTERLNBNK7'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.10/v/missing

and when i upload the datasets with sting values, it gives the following error message:

An error occurred: 1 validation error for PortfolioCompany user_fields Field required [type=missing, input_value={'company_name': 'Sterlin...y_isin': 'NGSTERLNBNK7'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.10/v/missing

**Comment by mountainrambler** [comment]
Perhaps there is a conflict between versions of Pydantic. The SBTi-finance-tool was developed using Pydantic 1.x while your error messages suggest that you have Pydantic 2.x installed in your environment. There were several breaking changes in Pydantic v2, so that will produce some errors when running the tool.

**Comment by VerdureClimateLtd** [comment]
This was so helpful, thank you so much. it works perfectly now.
